apiVersion: v1
kind: ConfigMap
metadata:
  name: market-service
  namespace: banka-1-dev
data:
  application.properties: |
    {
      "spring.datasource.url": "jdbc:postgresql://banka-1-ha:5432/bank_marketservice",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
      "oauth.jwt.secret": "secret_key",
      "listingAPItoken": "pk_f87286e075c94cc484405da70691c030",
      "alphaVantageAPIToken":"OF6BVKZOCXWHD9NS",
      "forexAPItoken": "cnr3i41r01qs2jr5d5bgcnr3i41r01qs2jr5d5c0",
      "listingNameApiUrl":"https://api.iex.cloud/v1/data/core/stock_collection/sector?collectionName=",
      "updateListingApiUrl":"https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=",
      "basicStockInfoApiUrl":"https://www.alphavantage.co/query?function=OVERVIEW&symbol=",
      "HistoryListingApiUrl":"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=",
      "forexExchangePlaceApiUrl":"https://finnhub.io/api/v1/forex/exchange?token=",
      "forexSymbolsApiUrl":"https://finnhub.io/api/v1/forex/symbol?exchange=",
      "forexExchangeRateApiUrl":"https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE",
      "forexDailyApiUrl":"https://www.alphavantage.co/query?function=FX_DAILY",
      "optionsUrl":"https://query2.finance.yahoo.com/v7/finance/options/",
      "springdoc.packagesToScan": "rs.edu.raf.banka1.controller",
      "dev.environment": false
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service
  namespace: banka-1-dev
  labels:
    service: market-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: market-service
  template:
    metadata:
      labels:
        service: market-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/market-service:latest
          imagePullPolicy: Always
          name: market-service
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: market-service
                  key: application.properties
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: banka-1-pguser-admin
                  key: user
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: banka-1-pguser-admin
                  key: password
            - name: spring.jpa.hibernate.ddl-auto
              value: update
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: market-service
  namespace: banka-1-dev
spec:
  selector:
    service: market-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
