apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: banka-1-dev
data:
  application.properties: |
    {
        "spring.datasource.url": "jdbc:postgresql://banka-1-ha:5432/bank_userservice",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.datasource.driver-class-name": "org.postgresql.Driver",
        "oauth.jwt.secret": "my_secret",
        "spring.mail.host":"smtp.gmail.com",
        "spring.mail.port":587,
        "spring.mail.username":"noreply.rafbanka1@gmail.com",
        "spring.mail.password":"fony nhtw hlah vzul",
        "spring.mail.properties.mail.smtp.auth":true,
        "spring.mail.properties.mail.smtp.starttls.enable":true,
        "server.port": 8080,
        "front.port": 4200,
        "springdoc.packagesToScan": "rs.edu.raf.banka1.controller",
        "exchangeRateAPIToken": "5eb8b116c5d704eea74c42f1",
        "exchangeRateApiUrl": "https://v6.exchangerate-api.com/v6/",
        "marketServiceUrl": "http://market-service:8081"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: banka-1-dev
  labels:
    service: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user-service
  template:
    metadata:
      labels:
        service: user-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/user-service:latest
          imagePullPolicy: Always
          name: user-service
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: user-service
                  key: application.properties
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: banka-1-pguser-admin
                  key: user
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: banka-1-pguser-admin
                  key: password
            - name: spring.jpa.hibernate.ddl-auto
              value: update
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: banka-1-dev
spec:
  selector:
    service: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
