apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banka-1-ingress-api
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/user-service(/|$)(.*)"
            backend:
              service:
                name: user-service
                port:
                  number: 8080
          - pathType: ImplementationSpecific
            path: "/market-service(/|$)(.*)"
            backend:
              service:
                name: market-service
                port:
                  number: 8081
          - pathType: ImplementationSpecific
            path: "/fetching-service(/|$)(.*)"
            backend:
              service:
                name: fetching-service
                port:
                  number: 8082
